[package]
name = "ULVM"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
reqwest = { version = "0.12.15", features = ["json", "blocking"] }
rusty-hook = "0.11.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
